#!/usr/bin/env python
# WSGI Handler sample configuration file.
#
# Change the appropriate settings below, in order to provide the parameters
# that would normally be passed in the command-line.
# (at least conf['addons_path'])
#
# For generic wsgi handlers a global application is defined.
# For uwsgi this should work:
#   $ uwsgi_python --http :9090 --pythonpath . --wsgi-file openerp-wsgi.py
#
# For gunicorn additional globals need to be defined in the Gunicorn section.
# Then the following command should run:
#   $ gunicorn openerp:service.wsgi_server.application -c openerp-wsgi.py

import os
import sys

OPENERP_ROOT_DIR = os.path.join(os.environ.get('OPENSHIFT_REPO_DIR', '.'), 'wsgi/openerp')
if OPENERP_ROOT_DIR not in sys.path:
    sys.path.append(OPENERP_ROOT_DIR)

import openerp

#----------------------------------------------------------
# Common
#----------------------------------------------------------
openerp.multi_process = True # Nah!

# Equivalent of --load command-line option
openerp.conf.server_wide_modules = ['web']
conf = openerp.tools.config

# Path to the OpenERP Addons repository (comma-separated for
# multiple locations)

conf['addons_path'] = os.path.join(OPENERP_ROOT_DIR, 'openerp/addons')

# Optional database config if not using local socket
conf['db_host']     = os.environ['OPENSHIFT_POSTGRESQL_DB_HOST']
conf['db_port']     = int(os.environ['OPENSHIFT_POSTGRESQL_DB_PORT'])
conf['db_user']     = os.environ['OPENSHIFT_POSTGRESQL_DB_USERNAME']
conf['db_name']     = os.environ['OPENSHIFT_APP_NAME']
conf['db_password'] = os.environ['OPENSHIFT_POSTGRESQL_DB_PASSWORD']

#----------------------------------------------------------
# Generic WSGI handlers application
#----------------------------------------------------------
application = openerp.service.wsgi_server.application

#----------------------------------------------------------
# Gunicorn
#----------------------------------------------------------
# Standard OpenERP XML-RPC port is 8069
#bind = '127.0.0.1:8069'
#pidfile = '.gunicorn.pid'
#workers = 4
#timeout = 240
#max_requests = 2000

#
# Below for testing only
#
if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    httpd = make_server('localhost', 8051, application)
    # Wait for a single request, serve it and quit.
    httpd.handle_request()

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
